kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: testflask
  labels:
    app: testflask
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "testflask:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "python:3.8-ubi8"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/ycechungAI/testFlask.git"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:ca90e0562d061fe8c99f92d96b3a148fb6a73b5150b8d49bcac4b1fb75cacb5b
  runPolicy: Serial
